#!/usr/bin/env bash

printf "\nAvailable environments \n\n"

# determine which environment is selected 
if [[ -z ~/.envy/etc/config.json ]]; then
  selected=`~/.envy/bin/JSON.sh < ~/.envy/etc/config.json | grep -m 1 "[\"environment\"]" | cut -d '"' -f4`
fi

environment_defs=($(ls -1 ~/.envy/environments/*.json 2>/dev/null))

# list files in .envy/environments
for def in "${environment_defs[@]}"
do
  name=`~/.envy/bin/JSON.sh < $def | grep -m 1 "[\"name\"]" | cut -d '"' -f4`

  if [[ -n "$name" ]]
  then
    if [ "$selected" == "$name" ]
    then
      printf "=> $name\n"
    else
      printf "   $name\n"
    fi
  fi
done

if [[ -z "$selected" ]]; then
  printf "=> System\n"
else
  printf "   System\n"
fi



